coins = {
    '$$$': 'Money',
    '10MT': '10M Token',
    '1337': '1337',
    '1ST': 'FirstBlood',
    '2GIVE': '2GIVE',
    '300': '300 Token',
    '42': '42-coin',
    '4CHN': 'ChanCoin',
    '611': 'SixEleven',
    '808': '808Coin',
    '888': 'OctoCoin',
    '8BIT': '8Bit',
    '9COIN': '9COIN',
    'ABC': 'Alphabit',
    'ABJ': 'Abjcoin',
    'ABN': 'Abncoin',
    'ABY': 'ArtByte',
    'AC': 'AsiaCoin',
    'ACC': 'AdCoin',
    'ACES': 'Aces',
    'ACN': 'Avoncoin',
    'ACOIN': 'Acoin',
    'ACP': 'AnarchistsPrime',
    'ACT': 'Achain',
    'ADA': 'Cardano',
    'ADC': 'AudioCoin',
    'ADCN': 'Asiadigicoin',
    'ADK': 'Aidos Kuneen',
    'ADL': 'Adelphoi',
    'ADST': 'AdShares',
    'ADT': 'adToken',
    'ADX': 'AdEx',
    'ADZ': 'Adzcoin',
    'AE': 'Aeternity',
    'AEON': 'Aeon',
    'AERM': 'Aerium',
    'AGLC': 'AgrolifeCoin',
    'AGRS': 'Agoras Tokens',
    'AHT': 'Bowhead',
    'AI': 'POLY AI',
    'AIB': 'Advanced Inte',
    'AION': 'Aion',
    'AIR': 'AirToken',
    'AKY': 'Akuya Coin',
    'ALIS': 'ALIS',
    'ALL': 'Allion',
    'ALQO': 'ALQO',
    'ALT': 'Altcoin',
    'ALTC': 'Antilitecoin',
    'ALTCOM': 'AltCommunity',
    'AMB': 'Ambrosus',
    'AMBER': 'AmberCoin',
    'AMM': 'MicroMoney',
    'AMMO': 'Ammo Rewards',
    'AMP': 'Synereo',
    'AMS': 'AmsterdamCoin',
    'ANC': 'Anoncoin',
    'ANI': 'Animecoin',
    'ANT': 'Aragon',
    'ANTI': 'AntiBitcoin',
    'ANTX': 'Antimatter',
    'APC': 'AlpaCoin',
    'APW': 'AppleCoin',
    'APX': 'APX',
    'ARB': 'ARbit',
    'ARC': 'Arcade Token',
    'ARCO': 'AquariusCoin',
    'ARDR': 'Ardor',
    'ARG': 'Argentum',
    'ARGUS': 'Argus',
    'ARI': 'Aricoin',
    'ARK': 'Ark',
    'ARN': 'Aeron',
    'ART': 'Maecenas',
    'ASAFE2': 'AllSafe',
    'ASN': 'Aseancoin',
    'AST': 'AirSwap',
    'ASTRO': 'Astro',
    'ATB': 'ATBCoin',
    'ATL': 'ATLANT',
    'ATM': 'ATMChain',
    'ATMC': 'ATMCoin',
    'ATMS': 'Atmos',
    'ATOM': 'Atomic Coin',
    'ATS': 'Authorship',
    'ATX': 'Artex Coin',
    'AU': 'AurumCoin',
    'AUR': 'Auroracoin',
    'AV': 'AvatarCoin',
    'AVT': 'Aventus',
    'AXIOM': 'Axiom',
    'B2B': 'B2B',
    'B2X': 'SegWit2x [Fut',
    'B3': 'B3Coin',
    'B@': 'Bankcoin',
    'BAC': 'BitAlphaCoin',
    'BAS': 'BitAsean',
    'BASH': 'LuckChain',
    'BAT': 'BatCoin',
    'BAY': 'BitBay',
    'BBP': 'BiblePay',
    'BBR': 'Boolberry',
    'BBT': 'BitBoost',
    'BCAP': 'BCAP',
    'BCC': 'BitConnect',
    'BCD': 'Bitcoin Diamo',
    'BCDN': 'BlockCDN',
    'BCF': 'Bitcoin Fast',
    'BCH': 'Bitcoin Cash',
    'BCN': 'Bytecoin',
    'BCO': 'BridgeCoin',
    'BCPT': 'BlockMason Cr',
    'BCX': 'BitcoinX [Fut',
    'BCY': 'Bitcrystals',
    'BDL': 'Bitdeal',
    'BELA': 'Bela',
    'BENJI': 'BenjiRolls',
    'BERN': 'BERNcash',
    'BEST': 'BestChain',
    'BET': 'BetaCoin',
    'BGR': 'Bongger',
    'BIGUP': 'BigUp',
    'BIOB': 'BioBar',
    'BIOS': 'BiosCrypto',
    'BIP': 'BipCoin',
    'BIRDS': 'Birds',
    'BIS': 'Bismuth',
    'BIT': 'First Bitcoin',
    'BITB': 'BitBean',
    'BITBTC': 'bitBTC',
    'BITCNY': 'bitCNY',
    'BITEUR': 'bitEUR',
    'BITGOLD': 'bitGold',
    'BITOK': 'Bitok',
    'BITS': 'Bitstar',
    'BITSILVER': 'bitSilver',
    'BITUSD': 'bitUSD',
    'BITZ': 'Bitz',
    'BIX': 'Bibox Token',
    'BLAS': 'BlakeStar',
    'BLAZR': 'BlazerCoin',
    'BLC': 'Blakecoin',
    'BLITZ': 'Blitzcash',
    'BLK': 'BlackCoin',
    'BLN': 'Bolenum',
    'BLOCK': 'Blocknet',
    'BLOCKPAY': 'BlockPay',
    'BLRY': 'BillaryCoin',
    'BLU': 'BlueCoin',
    'BLUE': 'BLUE',
    'BLX': 'Blockchain Index',
    'BLZ': 'BlazeCoin',
    'BMC': 'Blackmoon Crypto',
    'BNB': 'Binance Coin',
    'BNT': 'Bancor',
    'BNTY': 'Bounty0x',
    'BNX': 'BnrtxCoin',
    'BOAT': 'BOAT',
    'BOLI': 'Bolivarcoin',
    'BON': 'Bonpay',
    'BOS': 'BOScoin',
    'BOST': 'BoostCoin',
    'BOT': 'Bodhi',
    'BPC': 'Bitpark Coin',
    'BPL': 'Blockpool',
    'BQ': 'bitqy',
    'BRAIN': 'Braincoin',
    'BRAT': 'BROTHER',
    'BRD': 'Bread',
    'BRIA': 'BriaCoin',
    'BRIT': 'BritCoin',
    'BRK': 'Breakout',
    'BRO': 'Bitradio',
    'BRX': 'Breakout Stake',
    'BSC': 'BowsCoin',
    'BSD': 'BitSend',
    'BSN': 'Bastonet',
    'BSR': 'BitSoar',
    'BSTAR': 'Blackstar',
    'BSTY': 'GlobalBoost-Y',
    'BT1': 'BT1 [CST]',
    'BT2': 'BT2 [CST]',
    'BTA': 'Bata',
    'BTB': 'BitBar',
    'BTBc': 'Bitbase',
    'BTC': 'Bitcoin',
    'BTC2X': 'Bitcoin2x',
    'BTCA': 'Bitair',
    'BTCD': 'BitcoinDark',
    'BTCM': 'BTCMoon',
    'BTCR': 'Bitcurrency',
    'BTCRED': 'Bitcoin Red',
    'BTCS': 'Bitcoin Silver',
    'BTCZ': 'BitcoinZ',
    'BTDX': 'Bitcloud',
    'BTE': 'BitSerial',
    'BTG': 'Bitgem',
    'BTM': 'Bitmark',
    'BTPL': 'Bitcoin Planet',
    'BTQ': 'BitQuark',
    'BTS': 'BitShares',
    'BTSR': 'BTSR',
    'BTU': 'Bitcoin Unlim',
    'BTWTY': 'Bit20',
    'BTX': 'Bitcore',
    'BUB': 'Bubble',
    'BUCKS': 'SwagBucks',
    'BUMBA': 'BumbaCoin',
    'BUN': 'BunnyCoin',
    'BURST': 'Burst',
    'BUZZ': 'BuzzCoin',
    'BVC': 'BeaverCoin',
    'BWK': 'Bulwark',
    'BXC': 'Bitcedi',
    'BXT': 'BitTokens',
    'BYC': 'Bytecent',
    'C2': 'Coin2.1',
    'CAB': 'Cabbage',
    'CACH': 'CacheCoin',
    'CAG': 'Change',
    'CAGE': 'CageCoin',
    'CALC': 'CaliphCoin',
    'CANN': 'CannabisCoin',
    'CAPP': 'Cappasity',
    'CARBON': 'Carboncoin',
    'CASH': 'Cash Poker Pro',
    'CASINO': 'Casino',
    'CAT': 'Catcoin',
    'CBD': 'CBD Crystals',
    'CBX': 'Crypto Bullion',
    'CC': 'CyberCoin',
    'CCM100': 'CCMiner',
    'CCN': 'CannaCoin',
    'CCO': 'Ccore',
    'CCRB': 'CryptoCarbon',
    'CCT': 'Crystal Clear',
    'CDN': 'Canada eCoin',
    'CDT': 'CoinDash',
    'CESC': 'CryptoEscudo',
    'CF': 'Californium',
    'CFD': 'Confido',
    'CFI': 'Cofound.it',
    'CFT': 'CryptoForecast',
    'CHC': 'ChainCoin',
    'CHEAP': 'Cheapcoin',
    'CHESS': 'ChessCoin',
    'CHIPS': 'CHIPS',
    'CJ': 'Cryptojacks',
    'CLAM': 'Clams',
    'CLINT': 'Clinton',
    'CLOAK': 'CloakCoin',
    'CLUB': 'ClubCoin',
    'CME': 'Cashme',
    'CMP': 'Compcoin',
    'CMPCO': 'CampusCoin',
    'CMS': 'COMSA [XEM]',
    'CMT': 'Comet',
    'CNC': 'CHNCoin',
    'CND': 'Cindicator',
    'CNNC': 'Cannation',
    'CNO': 'Coin(O)',
    'CNT': 'Centurion',
    'CNX': 'Cryptonex',
    'COAL': 'BitCoal',
    'COB': 'Cobinhood',
    'COLX': 'ColossusCoinXT',
    'CON': 'PayCon',
    'CONX': 'Concoin',
    'COR': 'CORION',
    'CORG': 'CorgiCoin',
    'COSS': 'COSS',
    'COUPE': 'Coupecoin',
    'COVAL': 'Circuits of V',
    'COXST': 'CoExistCoin',
    'CPC': 'Capricoin',
    'CPN': 'CompuCoin',
    'CRAVE': 'Crave',
    'CRB': 'Creditbit',
    'CRC': 'CrowdCoin',
    'CRDNC': 'Credence Coin',
    'CREA': 'Creativecoin',
    'CRED': 'Verify',
    'CREDO': 'Credo',
    'CREVA': 'CrevaCoin',
    'CRM': 'Cream',
    'CRT': 'CRTCoin',
    'CRTM': 'Corethum',
    'CRW': 'Crown',
    'CRX': 'Chronos',
    'CRYPT': 'CryptCoin',
    'CSC': 'CasinoCoin',
    'CSNO': 'BitDice',
    'CTIC2': 'Coimatic 2.0',
    'CTIC3': 'Coimatic 3.0',
    'CTO': 'Crypto',
    'CTR': 'Centra',
    'CTX': 'CarTaxi Token',
    'CUBE': 'DigiCube',
    'CURE': 'Curecoin',
    'CV2': 'Colossuscoin V2',
    'CVC': 'Civic',
    'CVCOIN': 'CVCoin',
    'CWXT': 'CryptoWorldX',
    'CXT': 'Coinonat',
    'CYC': 'Cycling Coin',
    'CYDER': 'Cyder',
    'CYP': 'Cypher',
    'DAI': 'Dai',
    'DALC': 'Dalecoin',
    'DAR': 'Darcrus',
    'DASH': 'Dash',
    'DASHS': 'Dashs',
    'DAT': 'Datum',
    'DATA': 'Streamr DATAcoin',
    'DAV': 'DavorCoin',
    'DAXX': 'DaxxCoin',
    'DAY': 'Chronologic',
    'DBET': 'DecentBet',
    'DBG': 'Digital Bulli',
    'DBIX': 'DubaiCoin',
    'DBTC': 'Debitcoin',
    'DCN': 'Dentacoin',
    'DCR': 'Decred',
    'DCRE': 'DeltaCredits',
    'DCT': 'DECENT',
    'DCY': 'Dinastycoin',
    'DDF': 'DigitalDevelo',
    'DEM': 'Deutsche eMark',
    'DENT': 'Dent',
    'DES': 'Destiny',
    'DEUS': 'DeusCoin',
    'DEW': 'DEW',
    'DFS': 'DFSCoin',
    'DFT': 'DraftCoin',
    'DGB': 'DigiByte',
    'DGC': 'Digitalcoin',
    'DGCS': 'Digital Credits',
    'DGD': 'DigixDAO',
    'DGPT': 'DigiPulse',
    'DIBC': 'DIBCOIN',
    'DICE': 'Etheroll',
    'DIM': 'DIMCOIN',
    'DIME': 'Dimecoin',
    'DISK': 'DarkLisk',
    'DIVX': 'Divi',
    'DIX': 'Dix Asset',
    'DLC': 'Dollarcoin',
    'DLISK': 'DAPPSTER',
    'DLT': 'Agrello',
    'DMB': 'Digital Money',
    'DMC': 'DynamicCoin',
    'DMD': 'Diamond',
    'DNA': 'EncrypGen',
    'DNR': 'Denarius',
    'DNT': 'district0x',
    'DOGE': 'Dogecoin',
    'DOLLAR': 'Dollar Online',
    'DON': 'Donationcoin',
    'DOPE': 'DopeCoin',
    'DOT': 'Dotcoin',
    'DOVU': 'Dovu',
    'DP': 'DigitalPrice',
    'DPAY': 'DPAY',
    'DPY': 'Delphy',
    'DRGN': 'Dragonchain',
    'DRM': 'Dreamcoin',
    'DRP': 'DCORP',
    'DRS': 'Digital Rupees',
    'DRT': 'DomRaider',
    'DRXNE': 'DROXNE',
    'DSH': 'Dashcoin',
    'DSR': 'Desire',
    'DTB': 'Databits',
    'DTR': 'Dynamic Tradi',
    'DUB': 'Dubstep',
    'DUO': 'ParallelCoin',
    'DUTCH': 'Dutch Coin',
    'DYN': 'Dynamic',
    'E4ROW': 'E4ROW',
    'EAC': 'EarthCoin',
    'EAG': 'EA Coin',
    'EAGLE': 'EagleCoin',
    'EBCH': 'eBitcoinCash',
    'EBET': 'EthBet',
    'EBIT': 'eBIT',
    'EBST': 'eBoost',
    'EBT': 'Ebittree Coin',
    'EBTC': 'eBitcoin',
    'ECA': 'Electra',
    'ECASH': 'Ethereum Cash',
    'ECC': 'ECC',
    'ECN': 'E-coin',
    'ECO': 'EcoCoin',
    'ECOB': 'Ecobit',
    'EDG': 'Edgeless',
    'EDO': 'Eidoo',
    'EDOGE': 'EtherDoge',
    'EDR': 'E-Dinar Coin',
    'EDRC': 'EDRCoin',
    'EFL': 'e-Gulden',
    'EFYT': 'Ergo',
    'EGAS': 'ETHGAS',
    'EGC': 'EverGreenCoin',
    'EGG': 'EggCoin',
    'EGO': 'EGO',
    'EGOLD': 'eGold',
    'EL': 'Elcoin',
    'ELC': 'Elacoin',
    'ELE': 'Elementrem',
    'ELF': 'aelf',
    'ELITE': 'Ethereum Lite',
    'ELIX': 'Elixir',
    'ELLA': 'Ellaism',
    'ELS': 'Elysium',
    'ELTC2': 'eLTC',
    'ELTCOIN': 'ELTCOIN',
    'EMB': 'EmberCoin',
    'EMC': 'Emercoin',
    'EMC2': 'Einsteinium',
    'EMD': 'Emerald Crypto',
    'EMV': 'Ethereum Movi',
    'ENJ': 'Enjin Coin',
    'ENRG': 'Energycoin',
    'ENT': 'Eternity',
    'ENV': 'Environ',
    'EOS': 'EOS',
    'EOT': 'EOT Token',
    'EPY': 'Emphy',
    'EQT': 'EquiTrader',
    'ERC': 'EuropeCoin',
    'ERC20': 'ERC20',
    'EREAL': 'eREAL',
    'ERO': 'Eroscoin',
    'ERY': 'Eryllium',
    'ESP': 'Espers',
    'ETBS': 'Ethbits',
    'ETC': 'Ethereum Classic',
    'ETG': 'Ethereum Gold',
    'ETH': 'Ethereum',
    'ETHD': 'Ethereum Dark',
    'ETHOS': 'Ethos',
    'ETN': 'Electroneum',
    'ETP': 'Metaverse ETP',
    'ETT': 'EncryptoTel [',
    'EUC': 'Eurocoin',
    'EUSD': 'eUSD',
    'EVC': 'EventChain',
    'EVIL': 'Evil Coin',
    'EVO': 'Evotion',
    'EVR': 'Everus',
    'EVX': 'Everex',
    'EXCL': 'ExclusiveCoin',
    'EXN': 'ExchangeN',
    'EXP': 'Expanse',
    'EXRN': 'EXRNchain',
    'FAIR': 'FairCoin',
    'FAL': 'Falcoin',
    'FAP': 'FAPcoin',
    'FAZZ': 'Fazzcoin',
    'FBL': 'Faceblock',
    'FC': 'Facecoin',
    'FC2': 'FuelCoin',
    'FCN': 'Fantomcoin',
    'FCT': 'Factom',
    'FDC': 'Future Digita',
    'FFC': 'FireFlyCoin',
    'FID': 'BITFID',
    'FIL': 'Filecoin [Fut',
    'FIMK': 'FIMKrypto',
    'FIRE': 'Firecoin',
    'FJC': 'FujiCoin',
    'FLAP': 'FlappyCoin',
    'FLASH': 'Flash',
    'FLAX': 'Flaxscript',
    'FLDC': 'FoldingCoin',
    'FLIK': 'FLiK',
    'FLIXX': 'Flixxo',
    'FLO': 'FlorinCoin',
    'FLT': 'FlutterCoin',
    'FLVR': 'FlavorCoin',
    'FLY': 'Flycoin',
    'FNC': 'FinCoin',
    'FONZ': 'Fonziecoin',
    'FOR': 'FORCE',
    'FRAZ': 'Frazcoin',
    'FRC': 'Freicoin',
    'FRD': 'Farad',
    'FRGC': 'Fargocoin',
    'FRK': 'Franko',
    'FRN': 'Francs',
    'FRST': 'FirstCoin',
    'FRWC': 'FrankyWillCoin',
    'FST': 'Fastcoin',
    'FTC': 'Feathercoin',
    'FUCK': 'FuckToken',
    'FUDD': 'DimonCoin',
    'FUEL': 'Etherparty',
    'FUN': 'FunFair',
    'FUNC': 'FUNCoin',
    'FUNK': 'The Cypherfunks',
    'FUTC': 'FutCoin',
    'FUZZ': 'FuzzBalls',
    'FXE': 'FuturXe',
    'FYN': 'FundYourselfNow',
    'FYP': 'FlypMe',
    'G3N': 'G3N',
    'GAIA': 'GAIA',
    'GAIN': 'UGAIN',
    'GAM': 'Gambit',
    'GAME': 'GameCredits',
    'GAP': 'Gapcoin',
    'GARY': 'President Joh',
    'GAS': 'Gas',
    'GAY': 'GAY Money',
    'GB': 'GoldBlocks',
    'GBC': 'GBCGoldCoin',
    'GBG': 'Golos Gold',
    'GBRC': 'Global Busine',
    'GBT': 'GameBet Coin',
    'GBX': 'GoByte',
    'GBYTE': 'Byteball Bytes',
    'GCC': 'GuccioneCoin',
    'GCN': 'GCoin',
    'GCR': 'Global Curren',
    'GEERT': 'GeertCoin',
    'GEO': 'GeoCoin',
    'GIM': 'Gimli',
    'GLC': 'GlobalCoin',
    'GLD': 'GoldCoin',
    'GLS': 'GlassCoin',
    'GLT': 'GlobalToken',
    'GML': 'GameLeagueCoin',
    'GMT': 'Mercury Protocol',
    'GMX': 'GoldMaxCoin',
    'GNO': 'Gnosis',
    'GNT': 'Golem',
    'GNX': 'Genaro Network',
    'GOLF': 'Golfcoin',
    'GOLOS': 'Golos',
    'GOOD': 'Goodomy',
    'GP': 'GoldPieces',
    'GPL': 'Gold Pressed',
    'GPU': 'GPU Coin',
    'GRC': 'GridCoin',
    'GRE': 'Greencoin',
    'GRID': 'Grid+',
    'GRIM': 'Grimcoin',
    'GRN': 'Granite',
    'GRS': 'Groestlcoin',
    'GRT': 'Grantcoin',
    'GRWI': 'Growers Inter',
    'GRX': 'GOLD Reward T',
    'GSR': 'GeyserCoin',
    'GTC': 'Global Tour Coin',
    'GTO': 'Gifto',
    'GUC': 'GoldUnionCoin',
    'GUN': 'Guncoin',
    'GUP': 'Matchpool',
    'GVT': 'Genesis Vision',
    'GXS': 'GXShares',
    'HAL': 'Halcyon',
    'HALLO': 'Halloween Coin',
    'HAT': 'Hawala.Today',
    'HBN': 'HoboNickels',
    'HBT': 'Hubii Network',
    'HCC': 'Happy Creator',
    'HDG': 'Hedge',
    'HDLB': 'HODL Bucks',
    'HEAT': 'HEAT',
    'HERO': 'Sovereign Hero',
    'HGT': 'HelloGold',
    'HIGH': 'High Gain',
    'HMC': 'HarmonyCoin',
    'HMP': 'HempCoin',
    'HMQ': 'Humaniq',
    'HNC': 'Huncoin',
    'HODL': 'HOdlcoin',
    'HOLD': 'Interstellar',
    'HONEY': 'Honey',
    'HPC': 'Happycoin',
    'HSR': 'Hshare',
    'HST': 'Decision Token',
    'HTC': 'HitCoin',
    'HTML5': 'HTMLCOIN',
    'HUC': 'HunterCoin',
    'HUSH': 'Hush',
    'HVCO': 'High Voltage',
    'HVN': 'Hive',
    'HWC': 'HollyWoodCoin',
    'HXX': 'Hexx',
    'HYP': 'HyperStake',
    'HYPER': 'Hyper',
    'HYTV': 'Hyper TV',
    'I0C': 'I0Coin',
    'IBANK': 'iBank',
    'IBTC': 'iBTC',
    'ICE': 'iDice',
    'ICN': 'iCoin',
    'ICOB': 'ICOBID',
    'ICON': 'Iconic',
    'ICOO': 'ICO OpenLedger',
    'ICOS': 'ICOS',
    'ICX': 'ICON [Futures]',
    'IETH': 'iEthereum',
    'IFC': 'Infinitecoin',
    'IFLT': 'InflationCoin',
    'IFT': 'InvestFeed',
    'IGNIS': 'Ignis [Futures]',
    'IMPS': 'ImpulseCoin',
    'IMS': 'Independent M',
    'IMX': 'Impact',
    'INCNT': 'Incent',
    'IND': 'Indorse Token',
    'INDIA': 'India Coin',
    'INF': 'InfChain',
    'INFX': 'Influxcoin',
    'INK': 'Ink',
    'INN': 'Innova',
    'INPAY': 'InPay',
    'INSN': 'InsaneCoin',
    'INXT': 'Internxt',
    'IOC': 'I/O Coin',
    'ION': 'ION',
    'IOP': 'Internet of P',
    'IPY': 'Infinity Pay',
    'IQT': 'iQuant',
    'IRL': 'IrishCoin',
    'ISL': 'IslaCoin',
    'ITC': 'IoT Chain',
    'ITI': 'iTicoin',
    'ITNS': 'IntenseCoin',
    'ITT': 'Intelligent T',
    'ITZ': 'Interzone',
    'IVZ': 'InvisibleCoin',
    'IXC': 'Ixcoin',
    'IXT': 'iXledger',
    'J': 'Joincoin',
    'JET': 'Jetcoin',
    'JIN': 'Jin Coin',
    'JINN': 'Jinn',
    'JNS': 'Janus',
    'JOBS': 'JobsCoin',
    'JS': 'JavaScript Token',
    'JWL': 'Jewels',
    'KARMA': 'Karmacoin',
    'KASHH': 'KashhCoin',
    'KAYI': 'Kayicoin',
    'KBR': 'Kubera Coin',
    'KCS': 'KuCoin Shares',
    'KED': 'Darsek',
    'KEK': 'KekCoin',
    'KIC': 'KibiCoin',
    'KICK': 'KickCoin',
    'KIN': 'Kin',
    'KLC': 'KiloCoin',
    'KLN': 'Kolion',
    'KMD': 'Komodo',
    'KNC': 'KingN Coin',
    'KOBO': 'Kobocoin',
    'KORE': 'Kore',
    'KRB': 'Karbo',
    'KRONE': 'Kronecoin',
    'KURT': 'Kurrent',
    'KUSH': 'KushCoin',
    'LA': 'LAToken',
    'LANA': 'LanaCoin',
    'LAZ': 'Lazaruscoin',
    'LBC': 'LBRY Credits',
    'LBTC': 'LiteBitcoin',
    'LCP': 'Litecoin Plus',
    'LDCN': 'LandCoin',
    'LDOGE': 'LiteDoge',
    'LEA': 'LeaCoin',
    'LEND': 'ETHLend',
    'LEO': 'LEOcoin',
    'LEPEN': 'LePen',
    'LEX': 'Lex4All',
    'LGD': 'Legends Room',
    'LIFE': 'LIFE',
    'LINDA': 'Linda',
    'LINK': 'ChainLink',
    'LINX': 'Linx',
    'LIR': 'LetItRide',
    'LKC': 'LinkedCoin',
    'LKK': 'Lykke',
    'LLT': 'LLToken',
    'LMC': 'LoMoCoin',
    'LNK': 'Link Platform',
    'LOC': 'LockChain',
    'LOG': 'Woodcoin',
    'LOT': 'LottoCoin',
    'LRC': 'Loopring',
    'LSK': 'Lisk',
    'LTB': 'LiteBar',
    'LTC': 'Litecoin',
    'LTCR': 'Litecred',
    'LTCU': 'LiteCoin Ultra',
    'LTG': 'LiteCoin Gold',
    'LTH': 'LAthaan',
    'LUN': 'Lunyr',
    'LUNA': 'Luna Coin',
    'LUX': 'LUXCoin',
    'LVPS': 'LevoPlus',
    'MAC': 'Machinecoin',
    'MAD': 'SatoshiMadness',
    'MAG': 'Magnet',
    'MAGE': 'MagicCoin',
    'MAGN': 'Magnetcoin',
    'MAID': 'MaidSafeCoin',
    'MANA': 'Decentraland',
    'MAO': 'Mao Zedong',
    'MAR': 'Marijuanacoin',
    'MARS': 'Marscoin',
    'MARX': 'MarxCoin',
    'MAVRO': 'Mavro',
    'MAX': 'MaxCoin',
    'MAY': 'Theresa May Coin',
    'MBI': 'Monster Byte',
    'MBL': 'MobileCash',
    'MBRS': 'Embers',
    'MCAP': 'MCAP',
    'MCI': 'Musiconomi',
    'MCO': 'Monaco',
    'MCR': 'Macro',
    'MCRN': 'MACRON',
    'MDA': 'Moeda Loyalty',
    'MDS': 'MediShares',
    'MEC': 'Megacoin',
    'MED': 'Medibloc',
    'MEME': 'Memetic / Pep',
    'MEN': 'PeopleCoin',
    'MEOW': 'Kittehcoin',
    'MER': 'Mercury',
    'METAL': 'MetalCoin',
    'MGC': 'GulfCoin',
    'MGM': 'Magnum',
    'MGO': 'MobileGo',
    'MILO': 'MiloCoin',
    'MINEX': 'Minex',
    'MINT': 'Mintcoin',
    'MIOTA': 'IOTA',
    'MKR': 'Maker',
    'MLN': 'Melon',
    'MMXVI': 'MMXVI',
    'MNC': 'Mincoin',
    'MND': 'MindCoin',
    'MNE': 'Minereum',
    'MNM': 'Mineum',
    'MNX': 'MinexCoin',
    'MOD': 'Modum',
    'MOIN': 'Moin',
    'MOJO': 'MojoCoin',
    'MONA': 'MonaCoin',
    'MONETA': 'Moneta',
    'MONEY': 'MoneyCoin',
    'MONK': 'Monkey Project',
    'MOON': 'Mooncoin',
    'MOTO': 'Motocoin',
    'MRJA': 'GanjaCoin',
    'MRNG': 'MorningStar',
    'MRT': 'Miners Rewar',
    'MSCN': 'Master Swiscoin',
    'MSD': 'MSD',
    'MSP': 'Mothership',
    'MST': 'MustangCoin',
    'MTH': 'Monetha',
    'MTL': 'Metal',
    'MTLMC3': 'Metal Music Coin',
    'MTM': 'MTMGaming',
    'MTNC': 'Masternodecoin',
    'MUE': 'MonetaryUnit',
    'MUSIC': 'Musicoin',
    'MUT': 'Mutual Coin',
    'MXT': 'MarteXcoin',
    'MYB': 'MyBit Token',
    'MYST': 'Mysterium',
    'MZC': 'MazaCoin',
    'NAMO': 'NamoCoin',
    'NANOX': 'Project-X',
    'NAS': 'Nebulas',
    'NAV': 'NAV Coin',
    'NBE': 'BitCentavo',
    'NBIT': 'netBit',
    'NDC': 'NEVERDIE',
    'NEBL': 'Neblio',
    'NEO': 'NEO',
    'NEOG': 'NEO GOLD',
    'NEOS': 'NeosCoin',
    'NET': 'NetCoin',
    'NETKO': 'Netko',
    'NEVA': 'NevaCoin',
    'NEWB': 'Newbium',
    'NGC': 'NAGA',
    'NIO': 'Autonio',
    'NKA': 'IncaKoin',
    'NLC2': 'NoLimitCoin',
    'NLG': 'Gulden',
    'NMC': 'Namecoin',
    'NMR': 'Numeraire',
    'NOBL': 'NobleCoin',
    'NODC': 'NodeCoin',
    'NOTE': 'DNotes',
    'NRO': 'Neuro',
    'NSR': 'NuShares',
    'NTC': 'Natcoin',
    'NTO': 'Fujinto',
    'NTRN': 'Neutron',
    'NTWK': 'Network Token',
    'NUKO': 'Nekonium',
    'NULS': 'Nuls',
    'NVC': 'Novacoin',
    'NVST': 'NVO',
    'NXC': 'Nexium',
    'NXS': 'Nexus',
    'NXT': 'Nxt',
    'NYAN': 'Nyancoin',
    'NYC': 'NewYorkCoin',
    'OAX': 'OAX',
    'OBITS': 'OBITS',
    'OCEAN': 'BurstOcean',
    'OCL': 'Oceanlab',
    'OCOW': 'OCOW',
    'OCT': 'OracleChain',
    'ODN': 'Obsidian',
    'OFF': 'Cthulhu Offer',
    'OK': 'OKCash',
    'OMC': 'Omicron',
    'OMG': 'OmiseGO',
    'OMNI': 'Omni',
    'ONG': 'onG.social',
    'ONION': 'DeepOnion',
    'ONX': 'Onix',
    'OP': 'Operand',
    'OPAL': 'Opal',
    'OPES': 'Opescoin',
    'OPT': 'Opus',
    'ORB': 'Orbitcoin',
    'ORLY': 'Orlycoin',
    'ORME': 'Ormeus Coin',
    'OS76': 'OsmiumCoin',
    'OST': 'Simple Token',
    'OTN': 'Open Trading',
    'OTX': 'Octanox',
    'OX': 'OX Fina',
    'OXY': 'Oxycoin',
    'P7C': 'P7Coin',
    'PAC': 'Paccoin',
    'PAK': 'Pakcoin',
    'PART': 'Particl',
    'PASC': 'Pascal Coin',
    'PASL': 'Pascal Lite',
    'PAY': 'TenX',
    'PAYP': 'PayPeer',
    'PAYX': 'Paypex',
    'PBL': 'Publica',
    'PBT': 'Primalbase Token',
    'PCN': 'PeepCoin',
    'PCOIN': 'Pioneer Coin',
    'PCS': 'Pabyosi Coin',
    'PDC': 'Project Decorum',
    'PDG': 'PinkDog',
    'PEC': 'Peacecoin',
    'PEPECASH': 'Pepe Cash',
    'PEX': 'PosEx',
    'PFR': 'Payfair',
    'PGL': 'Prospectors Gold',
    'PHO': 'Photon',
    'PHR': 'Phore',
    'PHS': 'Philosopher S',
    'PIE': 'PIECoin',
    'PIGGY': 'Piggycoin',
    'PING': 'CryptoPing',
    'PINK': 'PinkCoin',
    'PIPL': 'PiplCoin',
    'PIRL': 'Pirl',
    'PIVX': 'PIVX',
    'PIX': 'Lampix',
    'PIZZA': 'PizzaCoin',
    'PKB': 'ParkByte',
    'PKT': 'Playkey',
    'PLACO': 'PlayerCoin',
    'PLBT': 'Polybius',
    'PLC': 'PlusCoin',
    'PLNC': 'PLNcoin',
    'PLR': 'Pillar',
    'PLU': 'Pluton',
    'PLX': 'PlexCoin',
    'PND': 'Pandacoin',
    'PNX': 'Phantomx',
    'POE': 'Po.et',
    'POKE': 'PokeCoin',
    'POLL': 'ClearPoll',
    'PONZI': 'PonziCoin',
    'POP': 'PopularCoin',
    'POS': 'PoSToken',
    'POST': 'PostCoin',
    'POSW': 'PoSW Coin',
    'POT': 'PotCoin',
    'POWR': 'Power Ledger',
    'PPC': 'Peercoin',
    'PPP': 'PayPie',
    'PPT': 'Populous',
    'PPY': 'Peerplays',
    'PR': 'Prototanium',
    'PRC': 'PRCoin',
    'PRE': 'Presearch',
    'PRES': 'President Trump',
    'PRG': 'Paragon',
    'PRIMU': 'Primulon',
    'PRIX': 'Privatix',
    'PRL': 'Oyster Pearl',
    'PRM': 'PrismChain',
    'PRN': 'Protean',
    'PRO': 'ProChain',
    'PROC': 'ProCurrency',
    'PRX': 'Printerium',
    'PST': 'Primas',
    'PSY': 'Psilocybin',
    'PTC': 'Pesetacoin',
    'PTOY': 'Patientory',
    'PULSE': 'Pulse',
    'PURA': 'Pura',
    'PURE': 'Pure',
    'PUT': 'PutinCoin',
    'PX': 'PX',
    'PXC': 'Phoenixcoin',
    'PXI': 'Prime-XI',
    'PZM': 'PRIZM',
    'Q2C': 'QubitCoin',
    'QASH': 'QASH',
    'QAU': 'Quantum',
    'QBC': 'Quebecoin',
    'QBK': 'Qibuck Asset',
    'QBT': 'Cubits',
    'QCN': 'QuazarCoin',
    'QORA': 'Qora',
    'QRK': 'Quark',
    'QRL': 'Quantum Resis',
    'QSP': 'Quantstamp',
    'QTL': 'Quatloo',
    'QTUM': 'Qtum',
    'QVT': 'Qvolta',
    'QWARK': 'Qwark',
    'R': 'Revain',
    'RADS': 'Radium',
    'RAIN': 'Condensate',
    'RBBT': 'RabbitCoin',
    'RBIES': 'Rubies',
    'RBT': 'Rimbit',
    'RBX': 'Ripto Bux',
    'RBY': 'Rubycoin',
    'RC': 'RussiaCoin',
    'RCN': 'Rcoin',
    'RDD': 'ReddCoin',
    'RDN': 'Raiden Networ',
    'REAL': 'REAL',
    'REC': 'Regalcoin',
    'RED': 'RedCoin',
    'REE': 'ReeCoin',
    'REGA': 'Regacoin',
    'REP': 'Augur',
    'REQ': 'Request Network',
    'REX': 'REX',
    'RHFC': 'RHFCoin',
    'RHOC': 'RChain',
    'RIC': 'Riecoin',
    'RICHX': 'RichCoin',
    'RIDE': 'Ride My Car',
    'RISE': 'Rise',
    'RIYA': 'Etheriya',
    'RKC': 'Royal Kingdom',
    'RLC': 'iExec RLC',
    'RLT': 'RouletteToken',
    'RMC': 'Remicoin',
    'RNS': 'Renos',
    'ROC': 'Rasputin Onli',
    'ROOFS': 'Roofs',
    'ROYAL': 'RoyalCoin',
    'RPC': 'RonPaulCoin',
    'RPX': 'Red Pulse',
    'RSGP': 'RSGPcoin',
    'RUBIT': 'RubleBit',
    'RUNNERS': 'Runners',
    'RUP': 'Rupee',
    'RUPX': 'Rupaya [OLD]',
    'RUSTBITS': 'Rustbits',
    'RVT': 'Rivetz',
    'RYZ': 'ANRYZE',
    'SAC': 'SACoin',
    'SAFEX': 'Safe Exchange',
    'SAGA': 'SagaCoin',
    'SAK': 'Sharkcoin',
    'SALT': 'SALT',
    'SAN': 'Santiment Net',
    'SANDG': 'Save and Gain',
    'SBC': 'StrikeBitClub',
    'SBD': 'Steem Dollars',
    'SBTC': 'Super Bitcoin',
    'SC': 'Siacoin',
    'SCL': 'Social',
    'SCORE': 'Scorecoin',
    'SCRT': 'SecretCoin',
    'SCS': 'Speedcash',
    'SCT': 'Soma',
    'SDC': 'ShadowCash',
    'SDP': 'SydPak',
    'SDRN': 'Senderon',
    'SEND': 'Social Send',
    'SEQ': 'Sequence',
    'SFC': 'Solarflarecoin',
    'SFE': 'SafeCoin',
    'SGR': 'Sugar Exchange',
    'SH': 'Shilling',
    'SHA': 'SHACoin',
    'SHDW': 'Shadow Token',
    'SHELL': 'ShellCoin',
    'SHIFT': 'Shift',
    'SHND': 'StrongHands',
    'SHORTY': 'Shorty',
    'SIB': 'SIBCoin',
    'SIFT': 'Smart Investm',
    'SIGMA': 'SIGMAcoin',
    'SIGT': 'Signatum',
    'SISA': 'SISA',
    'SJCX': 'Storjcoin X',
    'SKC': 'Skeincoin',
    'SKIN': 'SkinCoin',
    'SKR': 'Sakuracoin',
    'SKULL': 'Pirate Blocks',
    'SKY': 'Skycoin',
    'SLEVIN': 'Slevin',
    'SLFI': 'Selfiecoin',
    'SLG': 'Sterlingcoin',
    'SLING': 'Sling',
    'SLR': 'SolarCoin',
    'SLS': 'SaluS',
    'SMART': 'SmartBillions',
    'SMC': 'SmartCoin',
    'SMLY': 'SmileyCoin',
    'SMT': 'SmartMesh',
    'SNAKE': 'SnakeEyes',
    'SNC': 'SunContract',
    'SND': 'Sand Coin',
    'SNGLS': 'SingularDTV',
    'SNM': 'SONM',
    'SNOV': 'Snovio',
    'SNRG': 'Synergy',
    'SNT': 'Status',
    'SOAR': 'Soarcoin',
    'SOCC': 'SocialCoin',
    'SOIL': 'SOILcoin',
    'SOJ': 'Sojourn',
    'SONG': 'SongCoin',
    'SOON': 'SoonCoin',
    'SPACE': 'SpaceCoin',
    'SPANK': 'SpankChain',
    'SPEX': 'SproutsExtreme',
    'SPF': 'SportyFi',
    'SPHR': 'Sphere',
    'SPHTX': 'SophiaTX',
    'SPORT': 'SportsCoin',
    'SPR': 'SpreadCoin',
    'SPRTS': 'Sprouts',
    'SPT': 'Spots',
    'SRC': 'SecureCoin',
    'SSS': 'Sharechain',
    'STA': 'Starta',
    'STAR': 'Starbase',
    'STARS': 'StarCash Network',
    'START': 'Startcoin',
    'STC': 'Santa Coin',
    'STEEM': 'Steem',
    'STEPS': 'Steps',
    'STEX': 'STEX',
    'STORJ': 'Storj',
    'STORM': 'Storm',
    'STRAT': 'Stratis',
    'STRC': 'StarCredits',
    'STS': 'Stress',
    'STU': 'bitJob',
    'STV': 'Sativacoin',
    'STX': 'Stox',
    'SUB': 'Substratum',
    'SUMO': 'Sumokoin',
    'SUPER': 'SuperCoin',
    'SUR': 'Suretly',
    'SWIFT': 'Bitswift',
    'SWING': 'Swing',
    'SWP': 'Swapcoin',
    'SWT': 'Swarm City',
    'SXC': 'Sexcoin',
    'SYNC': 'Sync',
    'SYNX': 'Syndicate',
    'SYS': 'Syscoin',
    'TAAS': 'TaaS',
    'TAG': 'TagCoin',
    'TAGR': 'TAGRcoin',
    'TAJ': 'TajCoin',
    'TALK': 'BTCtalkcoin',
    'TCC': 'The ChampCoin',
    'TCOIN': 'T-coin',
    'TCR': 'TheCreed',
    'TEAM': 'TeamUp',
    'TEK': 'TEKcoin',
    'TELL': 'Tellurion',
    'TER': 'TerraNova',
    'TERA': 'TeraCoin',
    'TES': 'TeslaCoin',
    'TESLA': 'TeslaCoilCoin',
    'TFL': 'TrueFlip',
    'TGC': 'Tigercoin',
    'TGT': 'Target Coin',
    'THS': 'TechShares',
    'TIE': 'TIES Network',
    'TIME': 'Chronobank',
    'TIPS': 'FedoraCoin',
    'TIT': 'Titcoin',
    'TIX': 'Blocktix',
    'TKN': 'TokenCard',
    'TKR': 'CryptoInsight',
    'TKS': 'Tokes',
    'TLE': 'Tattoocoin',
    'TNB': 'Time New Bank',
    'TNT': 'Tierion',
    'TOA': 'ToaCoin',
    'TODAY': 'TodayCoin',
    'TOK': 'Tokugawa',
    'TOKEN': 'SwapToken',
    'TOP': 'TopCoin',
    'TOPAZ': 'Topaz Coin',
    'TOR': 'Torcoin',
    'TRADE': 'Tradecoin',
    'TRC': 'Terracoin',
    'TRCT': 'Tracto',
    'TRDT': 'Trident Group',
    'TRI': 'Triangles',
    'TRIA': 'Triaconta',
    'TRICK': 'TrickyCoin',
    'TRIG': 'Triggers',
    'TRK': 'Truckcoin',
    'TROLL': 'Trollcoin',
    'TRST': 'WeTrust',
    'TRUMP': 'TrumpCoin',
    'TRUST': 'TrustPlus',
    'TRX': 'TRON',
    'TSL': 'Energo',
    'TSTR': 'Tristar Coin',
    'TTC': 'TittieCoin',
    'TURBO': 'TurboCoin',
    'TX': 'TransferCoin',
    'TYCHO': 'Tychocoin',
    'TZC': 'TrezarCoin',
    'UAHPAY': 'UAHPay',
    'UBQ': 'Ubiq',
    'UBTC': 'United Bitcoin',
    'UET': 'Useless Ether',
    'UFO': 'UFO Coin',
    'UFR': 'Upfiring',
    'UGT': 'UG Token',
    'UIS': 'Unitus',
    'UKG': 'Unikoin Gold',
    'ULA': 'Ulatech',
    'UNB': 'UnbreakableCoin',
    'UNC': 'UNCoin',
    'UNI': 'Universe',
    'UNIC': 'UniCoin',
    'UNIFY': 'Unify',
    'UNIT': 'Universal Cur',
    'UNITS': 'GameUnits',
    'UNITY': 'SuperNET',
    'UNO': 'Unobtanium',
    'UNRC': 'UniversalRoya',
    'UNY': 'Unity Ingot',
    'UQC': 'Uquid Coin',
    'UR': 'UR',
    'URC': 'Unrealcoin',
    'URO': 'Uro',
    'USC': 'Ultimate Secu',
    'USDE': 'USDe',
    'USDT': 'Tether',
    'USNBT': 'NuBits',
    'UTA': 'UtaCoin',
    'UTC': 'UltraCoin',
    'V': 'Version',
    'VAL': 'Valorbit',
    'VASH': 'VPNCoin',
    'VC': 'VirtualCoin',
    'VEC2': 'VectorAI',
    'VEE': 'BLOCKv',
    'VERI': 'Veritaseum',
    'VET': 'VeChain',
    'VIA': 'Viacoin',
    'VIB': 'Viberate',
    'VIBE': 'VIBE',
    'VIDZ': 'PureVidz',
    'VIP': 'VIP Tokens',
    'VISIO': 'Visio',
    'VIU': 'Viuly',
    'VIVO': 'VIVO',
    'VLT': 'Veltor',
    'VLTC': 'Vault Coin',
    'VOISE': 'Voise',
    'VOLT': 'Bitvolt',
    'VOT': 'VoteCoin',
    'VOX': 'Voxels',
    'VOYA': 'Voyacoin',
    'VPRC': 'VapersCoin',
    'VRC': 'VeriCoin',
    'VRM': 'VeriumReserve',
    'VRS': 'Veros',
    'VSL': 'vSlice',
    'VSX': 'Vsync',
    'VTA': 'Virtacoin',
    'VTC': 'Vertcoin',
    'VTR': 'vTorrent',
    'VUC': 'Virta Unique',
    'VULC': 'Vulcano',
    'WA': 'WA Space',
    'WABI': 'WaBi',
    'WARP': 'WARP',
    'WAVES': 'Waves',
    'WAX': 'WAX',
    'WAY': 'WayGuide',
    'WBB': 'Wild Beast Block',
    'WC': 'WINCOIN',
    'WCT': 'Waves Communi',
    'WDC': 'WorldCoin',
    'WGO': 'WavesGo',
    'WGR': 'Wagerr',
    'WHL': 'WhaleCoin',
    'WIC': 'Wi Coin',
    'WILD': 'Wild Crypto',
    'WINGS': 'Wings',
    'WINK': 'Wink',
    'WISH': 'MyWish',
    'WMC': 'WMCoin',
    'WOMEN': 'WomenCoin',
    'WORM': 'HealthyWormCoin',
    'WOW': 'Wowcoin',
    'WRC': 'Worldcore',
    'WSX': 'WeAreSatoshi',
    'WTC': 'Walton',
    'WTT': 'Giga Watt Token',
    'WYV': 'Wyvern',
    'X2': 'X2',
    'XAS': 'Asch',
    'XAU': 'Xaucoin',
    'XAUR': 'Xaurum',
    'XBC': 'Bitcoin Plus',
    'XBL': 'Billionaire T',
    'XBTC21': 'Bitcoin 21',
    'XBTS': 'Beatcoin',
    'XBY': 'XTRABYTES',
    'XC': 'XCurrency',
    'XCN': 'Cryptonite',
    'XCO': 'X-Coin',
    'XCP': 'Counterparty',
    'XCPO': 'Copico',
    'XCRE': 'Creatio',
    'XCS': 'CybCSec',
    'XCT': 'C-Bit',
    'XCXT': 'CoinonatX',
    'XDE2': 'XDE II',
    'XDN': 'DigitalNote',
    'XEL': 'Elastic',
    'XEM': 'NEM',
    'XFT': 'Footy Cash',
    'XGOX': 'XGOX',
    'XGR': 'GoldReserve',
    'XHI': 'HiCoin',
    'XID': 'International',
    'XIN': 'Infinity Econ',
    'XIOS': 'Xios',
    'XJO': 'Joulecoin',
    'XLC': 'LeviarCoin',
    'XLM': 'Stellar',
    'XLR': 'Solaris',
    'XMCC': 'Monoeci',
    'XMG': 'Magi',
    'XMR': 'Monero',
    'XMY': 'Myriad',
    'XNG': 'Enigma',
    'XNN': 'Xenon',
    'XOC': 'Xonecoin',
    'XOT': 'Internet of T',
    'XP': 'Experience Po',
    'XPA': 'XPlay',
    'XPD': 'PetroDollar',
    'XPM': 'Primecoin',
    'XPTX': 'PlatinumBAR',
    'XPY': 'PayCoin',
    'XQN': 'Quotient',
    'XRA': 'Ratecoin',
    'XRB': 'RaiBlocks',
    'XRC': 'Rawcoin',
    'XRE': 'RevolverCoin',
    'XRL': 'Rialto',
    'XRP': 'Ripple',
    'XRY': 'Royalties',
    'XSH': 'SHIELD',
    'XSPEC': 'Spectrecoin',
    'XST': 'Stealthcoin',
    'XSTC': 'Safe Trade Coin',
    'XTD': 'XTD Coin',
    'XTO': 'Tao',
    'XTZ': 'Tezos',
    'XUC': 'Exchange Union',
    'XVC': 'Vcash',
    'XVE': 'The Vegan Ini',
    'XVG': 'Verge',
    'XVP': 'Virtacoinplus',
    'XWC': 'WhiteCoin',
    'XYLO': 'XYLO',
    'XZC': 'ZCoin',
    'YAC': 'Yacoin',
    'YASH': 'YashCoin',
    'YEL': 'Yellow Token',
    'YES': 'Yescoin',
    'YOC': 'Yocoin',
    'YOYOW': 'YOYOW',
    'YTN': 'YENTEN',
    'ZBC': 'Zilbercoin',
    'ZCG': 'ZCash Gold',
    'ZCL': 'ZClassic',
    'ZEC': 'Zcash',
    'ZEIT': 'Zeitcoin',
    'ZEN': 'ZenCash',
    'ZENGOLD': 'ZenGold',
    'ZENI': 'Zennies',
    'ZEPH': 'Zephyr',
    'ZER': 'Zero',
    'ZET': 'Zetacoin',
    'ZMC': 'ZetaMicron',
    'ZNE': 'Zonecoin',
    'ZNY': 'Bitzeny',
    'ZOI': 'Zoin',
    'ZRC': 'ZrCoin',
    'ZRX': '0x',
    'ZSC': 'Zeusshield',
    'ZSE': 'ZSEcoin',
    'ZUR': 'Zurcoin',
    'ZYD': 'Zayedcoin',
    'ZZC': 'ZoZoCoin'
    }
